<?
$PERM["ask"]["10"]="W";
$PERM["rew"]["9"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["lichnyy_kabinet_prodavtsa"]["2"]="D";
$PERM["lichnyy_kabinet_prodavtsa"]["3"]="D";
$PERM["lichnyy_kabinet_prodavtsa"]["4"]="D";
$PERM["lichnyy_kabinet_prodavtsa"]["6"]="D";
$PERM["lichnyy_kabinet_prodavtsa"]["5"]="D";
$PERM["lichnyy_kabinet_pokupatelya"]["2"]="D";
$PERM["lichnyy_kabinet_pokupatelya"]["3"]="D";
$PERM["lichnyy_kabinet_pokupatelya"]["4"]="D";
$PERM["lichnyy_kabinet_pokupatelya"]["7"]="D";
$PERM["lichnyy_kabinet_pokupatelya"]["5"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["/"]["*"]="R";
?>